addons:
  chrome: stable
  firefox: latest
language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew -Dgeb.env=chromeHeadless test"
- "./gradlew shadowJar"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: eu-west-1
  app: greachagenda
  env: Greachagenda-env
  on:
    tags: true
    branch: master
    repo: greach/agenda
  zip_file: build/libs/agenda-0.37.jar
  bucket_name: "$BUCKETNAME"
env:
  global:
  - secure: I2v2+hiaQ6OY1WgJF4c7cmnHOOwQZo3V0ZitLOsAaXCj9Wl0UxnWWDn9hpmxM1G5ZeWSr3udr7S2ZQ/eHxlRV29F5ZtO8kXXWJ5q7lyTDkeECfNrtZhlBbASEoIVKUvML4Lm+kl0WkJ455NNwHa9F0GT826raLe4e/YkabUbfkyjkYP5tG8pXSvWxS6StzFYjE5nXEI35OmhDC+0SaBT4Xzb0Im96T0qR+j+1dX3greEmhZi62f+UukSMTexd96O5MqmjyD3LHSWDuHWkNECyqetdOCnLSfM0K39QshNQUo1bP9+ZlvMLhBVVVN7QXt2fMoSFdZcjh4cOKA8zBSRbHpRJBT2U18g++uk026LxNGrZ4zVa90RAft+rInk3bGCe1k+bFlbI8ay3/o4DNdq0MG5924+KplqnLCf/9Aqoskumfd1iR/ilLP8ZVlSEYBmlGUtyJye+9IzyffbIVDfATLKt0zW6H1YJAeQ/nM9WU2jb7R8LsDuFGlp6TU+/CC80BvYIUqlfimZ6xATZvfZVCM50Tsul8feq1HHR0GP4tuVaitCyJ1O+FyV9hRTBUeYoEeSjFWXBV1yYx0pHySI0Rq/W931Da4RxFEhCllEtbKpd9o0M9ZCA2QY6Z2mn3cD7VImXGcUQ2v2/aFJyWBtazejnf6K7J8zjNCtR0kKOsM=
  - secure: PeGRVfuw5EJGc3X/HXSiyR68u3lR0e2I4lzpUolfp1+BaBb4bH/9s6RrwY8EHptY3Tchab2lVQHpIstEPSIAvEMJTnOUu7R0wRw1cuPfeyIE2Gm+y5omJp8H8TLpFsVz13IO/DPs7s+NWsUDY0aklIiP9Pa63NECLwinLLoy0RLYQ/JX3rVniyL2KnnSF4qO/xsKVViUH+6KsnCwy6RuEnc4CXZxTPqRnFAkgkjuU8I47zi2//I8JMvU9vyFSVX2Hs+znaKiEraSxK4Sjuuo0IZL7fBMxUDhH+7ONxTlcAgBH2d8HaBCBzFDFVkCVsJSJwiXgULFfKElk9K/dfUmm3GdMhej1iw1ZX7XqEqb9XzvAKuhuxJ3+R6LoUWMKY39bp/SEIpZmMADNScsJjFL/aoA7m39WbbCyV0pXnFJaE+BPOguho6yFrglTnovI+ac2m/wqjvmcPYh4odt+ZYLN1fmtyQ8KE3ms+RKEHqdRKmaw6xKMK2JwIeXg4pWMDMgCEFIk4PktCFcDqMXKGLivDXMhVJ0fcyLUYdMf94CfbWPhnXzTf3Ka2wk3bscqC/3Jdn8/Qneok8q/n0xBsB/Z4s4MDlLObAICCZgx4dyFTk1t+c/EhL6VD0R5HtNmIiccGHq0s7UTM7MtixZdt52WDNdocaOyUwnqyoID7TlCrQ=
  - secure: WV4IoUVZ1zvEC3h/bMHhT0AwTH52fLGp8opJQeRFNR+PS4GS/78Q+9Cy7Fg7uEe+V7bVXMmX6nOWiWVeSnK7K9Caf4Ag1rI5bu9y4HM/6UzoUD22xOCp1SyKgGcngZQ7hOF+8+Gb3juJ0W/MwOY3OITY1xxgkmkTd4v4sb4ZcsJsF3YEXL4/JHmkZiyarTZW0DtidNZthCrgWP35opxlLZt5rel0sni31HJnCP3bu3sHkYZkSepHZElmgxou3hrW+pMN2bkKMeq4P7Ymdl9qi6z/ltL51uVOVJGD/2QdVsoHrdUhCvgFtPtFDhCU1FyFq5vLBonFcXybeBeuzd7wTeIqFIynEYAShlnAyY2rCrX9Gglb+++Rs7nMVSysjKlqRU3XPyKlqBN8ixmB1sl5m0zDaByge7IvaePIbG3J0symgpn3rbhDkyr+6GnuJlghr8ziOAVhZVdCFTnH57IoQbO6HiSt+e6fRUPg+fCxUY+53DNAYNqPhShnQVD3u9T2lRD+7gSBHvyNicsn67ixEiytJgm4SP6tl6u7K5L87jhrt8Wv4lUeXb06cyUSB2C1qkILWrYDGGqQ57uIhCv5MvA6FL8OFrlKUw45WeNF299UzfaPuJ4MhyWQf4Hu2waUXALEsp3s4LxPIwReC3aZ6xRE2jGJxkxNB85wiOTaZdk=
